### ISSUE TITLE
Fix PE parsing of VersionString

### ISSUE THREAD

**Issue by cen1** [BNETDocs/bncsutil#6]
With Warcraft 3 1.27a the VersionString parsing from PE is completely broken. Research notes:
1. What is actually sent to bnet for exampe from ghost++: verstr=`1.246.162.18`. Even more bizarre is that different people got different VersionString results on 1.27a..
2.  What we actually need: `1.27.0.16` (this is sent to bnet if you login via w3 client, I believe in reversed order)

Problem is in function `getExeInfo()` in `checkrevision.cpp` where the UNIX code is #ifdefed with custom PE parser while Windows one uses WINAPI and therefore works correctly. I believe the actual function doing the read is `cm_pe_fixed_version()` in `pe.c`.

Additionally, I found a lib https://github.com/merces/libpe which implements a PE parser. Unfortunately, pev lib shows 1.27.0.52240, the same as Windows Explorer (if you right click on war3.exe and go to properties you will see that number)! It looks like the patch version is calculated in some different way by w3 client.

Finally, official bnet does not enforce correct VersionSring anyway but PvPGN has an option to do so (and we do actually use this in production).

I'm opening this issue just to make it public knowledge that the bug exists, I'm not sure I'll have time or willpower to tackle it but it can be a nice summer project for someone.

**Comment by CHOB-HET** [comment]
easy patch
[patch.txt](https://github.com/BNETDocs/bncsutil/files/524871/patch.txt)

**Comment by carlbennett** [comment]
@CHOB-HET, I've created a pull request with your changes here: #8

**Comment by cen1** [comment]
I'll test this tomorrow. Thanks for the patch.

**Comment by cen1** [comment]
Looks good. Compiled atop of my branch, linked to ghost++, logged to pvpgn. Hex to server: 10 00 1b 01 (1.27.0.16 in reverse).

**Comment by carlbennett** [comment]
#8 has been merged. Please verify if this issue is now fixed and can be closed.

**Comment by cen1** [comment]
Successful login to eurobattle.net without having to specify custom version exe hash. Signed off by me.
